# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def using_pods    
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # all pods define here
  pod 'SwiftLint'
  pod 'Alamofire', '~> 4.4'
  pod 'PromiseKit', '~> 4.2.0'
  pod 'ObjectMapper', '~> 2.2'
  pod 'Firebase/Core'
end

target 'FireNotes' do
  using_pods
end
