# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def using_pods    
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # all pods defined here
  pod 'SwiftLint'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
end

target 'FireNotes' do
  using_pods
end
